### PR TITLE
[resource] Thread-safe Resource

### PR DESCRIPTION
**Pull request by joaofel-u**
# Description #
In this PR, we add a Spinlock to guarantee thread-safeness when allocating and freeing a resource from a resource pool. This enhancement was introduced to avoid data race conditions in scenarios where multiple threads compete for a specific resource allocation.

### CODE REVIEW

**Review by joaovicentesouto — APPROVED** [review]
That's sounds good, approved.

I just have a few observations:
- The resource abstraction was primordially thought to not be thread-safe but it's ok to insert this protection.
- The global lock is good because we save memory by avoiding put the spinlock inside the structs but this affects all the system. However, the operations are simple, so that overhead will be small.
- In the future, maybe we can create wrapper functions that handle the spinlock and call the raw resource functions (not thread-safe). So only those who really have concurrence and parallelism on its operations can suffer this overhead.

**Comment by joaofel-u** [comment]
> * The resource abstraction was primordially thought to not be thread-safe but it's ok to insert this protection.
> * The global lock is good because we save memory by avoiding put the spinlock inside the structs but this affects all the system. However, the operations are simple, so that overhead will be small.
> * In the future, maybe we can create wrapper functions that handle the spinlock and call the raw resource functions (not thread-safe). So only those who really have concurrence and parallelism on its operations can suffer this overhead.

I agree with @joaovicentesouto observations, especially the third point. I did not include a similar solution for this in this PR because it was not the focus of it. However, this may become a good first issue to be implemented, along with an additional routine that enables thread-safeness for a specific resource_pool, additionally to the standard behavior of being not thread-safe.

What are your thoughts @ppenna?

**Comment by joaovicentesouto** [comment]
Very good points. Reading @joaofel-u 's observations, I think that the extra memory space can be avoided by passing the lock to the function. Thus, a resource poll can be protected or not by the user, just the user keeps and uses an external lock. If it's NULL (or a wrapper function without the lock parameter) and wants to use the protection anyway, so we use the global lock.

**Comment by ppenna** [comment]
Hello, I liked the ideas suggested by @joaofel-u Besides, it look good for me to have a global spinlock to save some memory. Approved =D

**Review by ppenna — APPROVED** [review]

**Review by ppenna — APPROVED** [review]

**Pull request merged**
